name: Deploy to InfinityFree

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mysqli, json, ftp, zip
        coverage: xdebug
        
    - name: Install Dependencies
      run: |
        composer install --prefer-dist --no-progress
        
    - name: Run Tests
      run: |
        vendor/bin/phpunit
        
    - name: Run PHPCS
      run: |
        vendor/bin/phpcs
        
    - name: Run PHPStan
      run: |
        vendor/bin/phpstan analyse

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mysqli, json, ftp, zip
        
    - name: Install Dependencies
      run: |
        composer install --prefer-dist --no-progress --no-dev
        
    - name: Create Deployment Package
      run: |
        php deploy-to-infinity.php
        
    - name: Deploy to InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ${{ secrets.FTP_SERVER_DIR }} 