name: Deploy to InfinityFree

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mysqli, json, ftp, zip
        coverage: xdebug
        
    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
        
    - name: Install Dependencies
      run: |
        composer install --prefer-dist --no-progress --no-interaction
        
    - name: Run Tests
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: test_db
        DB_USERNAME: root
        DB_PASSWORD: root
      run: |
        vendor/bin/phpunit --debug --verbose
        
    - name: Run PHPCS
      run: |
        vendor/bin/phpcs --standard=PSR12 crbs-core/application || true
        
    - name: Run PHPStan
      run: |
        vendor/bin/phpstan analyse --no-progress || true

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mysqli, json, ftp, zip
        
    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
        
    - name: Install Dependencies
      run: |
        composer install --prefer-dist --no-progress --no-dev --no-interaction
        
    - name: Prepare for Deployment
      run: |
        # Update the database configuration for InfinityFree
        php deploy.php
        
        # Create necessary directories if they don't exist
        mkdir -p dist
        
        # Copy essential files to dist directory
        cp -r index.php .htaccess LICENSE.txt dist/
        cp -r crbs-core dist/
        cp -r assets dist/
        
        # Create empty directories that might be needed
        mkdir -p dist/uploads
        mkdir -p dist/local/logs
        mkdir -p dist/local/cache
        mkdir -p dist/local/sessions
        
        # Create placeholder files to ensure directories are kept
        touch dist/uploads/index.html
        touch dist/local/logs/index.html
        touch dist/local/cache/index.html
        touch dist/local/sessions/index.html
        
    - name: Deploy to InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: ${{ secrets.FTP_SERVER_DIR }}
        dangerous-clean-slate: false